name: Api Build & Test & Deploy

on:
  push:
    branches: [ master ]
    paths: [ 'api/**/*' ]
    
jobs:
  build-api:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - run: go build .

  deploy-api:
    needs: [build-api]

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12

        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "ytmparty-api"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "api"
          
  announce-api:
    needs: [deploy-api]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: appleboy/discord-action@master

        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          args: "Api pipeline successfully passed. Deployed to heroku."
