name: Client Build & Test & Deploy

on:
  push:
    branches: [ master ]
    paths: [ 'client/**/*' ]

jobs:
  install-client:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install


  build-client:

    needs: [install-client]

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn run build

  
  test-client:
    needs: [ build-client ]

    runs-on: ubuntu-latest
      
    defaults:
        run:
          working-directory: ./client
      
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn run test