name: Client Build & Test & Deploy

on:
  push:
    branches: [ master ]
    paths: [ 'client/**/*' ]

jobs:
  install-client:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - run: npm ci
        

  build-client:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2
      - run: npm run build

  
  test-client:
    
    runs-on: ubuntu-latest
      
    defaults:
        run:
          working-directory: ./client
      
    steps:
      - uses: actions/checkout@v2
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI