name: Client Build & Test & Deploy

on:
  push:
    branches: [ master ]
    paths: [ 'client/**/*' ]

jobs:
  install-client:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --cache-folder ${{ steps.yarn-cache.outputs.path }}


  build-client:

    needs: [install-client]

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2
      - run: npm run build

  
  test-client:
    needs: [ build-client ]

    runs-on: ubuntu-latest
      
    defaults:
        run:
          working-directory: ./client
      
    steps:
      - uses: actions/checkout@v2
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI